### ISSUE TITLE
gow to build it?

### ISSUE THREAD

**Issue by rafalohaki** [catgirls-top/hyofu#11]
how to build and deploy it?

**Comment by hernikplays** [comment]
If you're running 1.0, there is a README in the .zip file. The version currently on the master branch is nowhere near ready for deployment

**Comment by rafalohaki** [comment]
where to edit token?

**Comment by rafalohaki** [comment]
got config for sharex but seems nmot working
{
  "Version": "13.3.0",
  "DestinationType": "ImageUploader",
  "RequestMethod": "POST",
  "RequestURL": "http://myhost/upload",
  "Headers": {
    "token": "[insert user token here]"
  },
  "Body": "MultipartFormData",
  "FileFormName": "file",
  "URL": "$json:response$",
  "DeletionURL": "$json:delurl$",
  "ErrorMessage": "$json:error$"
}
